# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fa13c1dc-f340-432e-848b-50de9d3bf092";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fa13c1dc-f340-432e-848b-50de9d3bf092".device = "/dev/disk/by-uuid/fa13c1dc-f340-432e-848b-50de9d3bf092";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7111-C665";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-e502d131-645e-4e13-8639-f91fc78167f7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
