name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
#      - name: Install Nix
#        run: |
#          curl -L https://nixos.org/nix/install | sh
#          . $HOME/.nix-profile/etc/profile.d/nix.sh
#      - name: Set up Nix build environment
#        run: nix-shell '<nixpkgs>' -A haskellPackages.ghc
#      - name: Update Nix channels
#        run: nix-channel --update
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Get attic
      #   run: nix-shell https://github.com/zhaofengli/attic/tarball/main -A demo --run "attic login server https://nix-cache.qownnotes.org $ATTIC_SECRET_KEY"
      #   env:
      #     ATTIC_SECRET_KEY: ${{ secrets.ATTIC_SECRET_KEY }}
      - name: Build qc package
        run: |
          cd apps/qc && \
          nix-build -E '((import <nixpkgs> {}).callPackage (import ./default.nix) { })' && \
          ls -hal
          # nix-shell https://github.com/zhaofengli/attic/tarball/main -A demo --run "attic push qownnotes ./results/*"
      - name: Build qownnotes package
        run: |
          cd apps/qownnotes && \
          nix-build -E '((import <nixpkgs> {}).qt6Packages.callPackage (import ./default.nix) { })' && \
          nix-shell https://github.com/zhaofengli/attic/tarball/main -A demo --run "attic push qownnotes ./results/*"
