name: 🔎️ Check flake for all systems

on:
  push:
    paths-ignore:
      - 'docker/**'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docker/**'
  repository_dispatch:
    types: [trigger-checks]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check flake for all systems
        run: nix flake check --no-build --keep-going
